"""Add reset_token and expiry to User

Revision ID: 6393776f9cb1
Revises: 8fdd8ca9b881
Create Date: 2025-06-18 19:25:22.189757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6393776f9cb1'
down_revision = '8fdd8ca9b881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reset_token_expiry')
        batch_op.drop_column('reset_token')

    # ### end Alembic commands ###
