"""Add inviter_id FK with explicit name

Revision ID: 6af49a1e3ac4
Revises: 9cdea5160338
Create Date: 2025-06-23 22:07:00.485069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af49a1e3ac4'
down_revision = '9cdea5160338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_invite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inviter_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_group_invite_inviter_id_users', 'users', ['inviter_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_invite', schema=None) as batch_op:
        batch_op.drop_constraint('fk_group_invite_inviter_id_users', type_='foreignkey')
        batch_op.drop_column('inviter_id')

    # ### end Alembic commands ###
