"""Add GroupInvite model

Revision ID: 7517ae4e40ad
Revises: 8769999e7213
Create Date: 2025-06-17 17:43:47.580142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7517ae4e40ad'
down_revision = '8769999e7213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('token', sa.String(length=128), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_invite')
    # ### end Alembic commands ###
