"""improving roles etc

Revision ID: 9753d85dad51
Revises: d8ea98e022ad
Create Date: 2025-06-16 21:02:46.099240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9753d85dad51'
down_revision = 'd8ea98e022ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_admins',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('verification_token', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('verification_token')
        batch_op.drop_column('is_verified')

    op.drop_table('group_admins')
    # ### end Alembic commands ###
