"""Add user preferences

Revision ID: 9cdea5160338
Revises: d14902e3025b
Create Date: 2025-06-22 22:03:11.669740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cdea5160338'
down_revision = 'd14902e3025b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_preference', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('notify_group_activity', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_public_profile', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_public_profile')
        batch_op.drop_column('notify_group_activity')
        batch_op.drop_column('unit_preference')

    # ### end Alembic commands ###
