"""Switch distance from meters (int) to kilometers (numeric)

Revision ID: d14902e3025b
Revises: 6393776f9cb1
Create Date: 2025-06-20 20:14:30.453556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd14902e3025b'
down_revision = '6393776f9cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.alter_column('distance',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=8, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('runs', schema=None) as batch_op:
        batch_op.alter_column('distance',
               existing_type=sa.Numeric(precision=8, scale=2),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
